### PR TITLE
fix: Implement permission checking and basic error handling.

### LINKED ISSUE #22: Unprivileged command execution
Lack of permission checks  could lead to unprivileged command execution.

### PR DESCRIPTION
**Pull request by ChecksumDev**
Requires testing / review.
Fixes #22

### CODE REVIEW

**Comment by ChecksumDev** [comment]
I'm not sure how the Bukkit permission checks will interact with the ones specified in this PR, I'm assuming they will be overridden by Bukkit but its better safe than sorry.

**Review by sargon64 — CHANGES_REQUESTED** [review]
src/kotlin/moe/velvet/infernalmobs/Loot.kt must not use property access syntax.

**Comment by ChecksumDev** [comment]
> src/kotlin/moe/velvet/infernalmobs/Loot.kt must not use property access syntax.

Ah I wasn't aware this was changed, my editor must of automatically ran the code cleanup. Let me revert it.

**Review by sargon64 — APPROVED** [review]
LGTM

**Pull request merged**
